# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dftest <- function(df, vname) {
    .Call('_MethyAge2_dftest', PACKAGE = 'MethyAge2', df, vname)
}

rcpp_hello <- function() {
    .Call('_MethyAge2_rcpp_hello', PACKAGE = 'MethyAge2')
}

