# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title dftest a example for Rcpp
#' @description it is a example for Rcpp and devtools, which extract a column of a dataframe
#' @param df a data frame
#' @param vanme name of the col you wanna extract
#' @return a vector which is the col you select
#' @examples
#' test<-data.frame(a = rep(1,5),b = rep(4,5))
#' aaa<-dftest(test,"a")
dftest <- function(df, vname) {
    .Call('_MethyAge2_dftest', PACKAGE = 'MethyAge2', df, vname)
}

rcpp_hello <- function() {
    .Call('_MethyAge2_rcpp_hello', PACKAGE = 'MethyAge2')
}

